### ISSUE TITLE
Chef::Exceptions with the 'default['java']['openjdk_version'] = nil' attribute 

### ISSUE THREAD

**Issue by aphexlog** [sous-chefs/java#490]
# default jdk attributes
default['java']['jdk_version'] = '6'
default['java']['arch'] = node['kernel']['machine'] =~ /x86_64/ ? 'x86_64' : 'i586'
default['java']['openjdk_packages'] = []
default['java']['openjdk_version'] = nil

Is the openjdk_version attribute expecting the user to modify the value from nil? Because when converging kitchen I receive the following error:
`FATAL: Chef::Exceptions::Package: yum_package[java-1.6.0-openjdk, java-1.6.0-openjdk-devel] (java::openjdk line 40) had an error: Chef::Exceptions::Package: No candidate version available for java-1.6.0-openjdk, java-1.6.0-openjdk-devel`

```
chef --version
Chef Development Kit Version: 3.2.30
chef-client version: 14.4.56
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 2.2.70
```

kitchen.yml=
```
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: rhel7
    driver:
      box: generic/rhel7
      box_url: generic/rhel7

suites:
  - name: default
    run_list:
      - recipe[java::default]
```
